### ISSUE TITLE
pw::Application exit while using port=0

### ISSUE THREAD

**Issue by michaeljefferies** [pointwise/GlyphClientPython#1]
The following script will cause socket failure exceptions rather than cleanly shutting down Pointwise and allowing the script to continue.  While it may be the case that exception handling should be added to a script to ensure it continues running despite what happens inside of Pointwise, a properly executed glyph command like "pw::Application exit" shouldn't cause an exception to escape outside of the GlyphClientPython module.

```python
#! /usr/bin/env python3
from pointwise import GlyphClient

with GlyphClient(port=0) as glf:
    glf.eval("pw::Application exit")

print("Script is still running")
```

**Comment by pabakertx** [comment]
This is resolved with 2.0.1, available here on github and via pip.
