### ISSUE TITLE
How can I control pointwise to read test.glf script files through python

### ISSUE THREAD

**Issue by wth666** [pointwise/GlyphClientPython#3]
How can I control pointwise to read test.glf script files through python
![image](https://user-images.githubusercontent.com/121304181/209358484-b295a72d-584e-4827-a0eb-946be844b3bb.png)
This doesn't work

**Comment by pabakertx** [comment]
"pw::Script" is a command only available when running in a tclsh directly, as it's part of the interpreter's namespace, not part of the Glyph server. This works, though:

pw.glf.eval("source test.glf")

Caveat: Don't call 'exit' or 'pw::Application exit' within your script or the server process will shut down.
